yarnPath: ".yarn/releases/yarn-berry.cjs"

nodeLinker: pnp

npmRegistries:
  //gitlab.com/api/v4/packages/npm:
    npmAuthToken: dLKL8ua11NwAKhdFyDQZ
  //gitlab.com/api/v4/projects/17986031/packages/npm:
    npmAuthToken: dLKL8ua11NwAKhdFyDQZ
  //gitlab.com/api/v4/projects/18567235/packages/npm:
    npmAuthToken: dLKL8ua11NwAKhdFyDQZ
  //gitlab.com/api/v4/projects/20861715/packages/npm:
    npmAuthToken: dLKL8ua11NwAKhdFyDQZ
  //gitlab.com/api/v4/projects/20934408/packages/npm:
    npmAuthToken: dLKL8ua11NwAKhdFyDQZ
  //gitlab.com/api/v4/projects/20980429/packages/npm:
    npmAuthToken: dLKL8ua11NwAKhdFyDQZ
  //gitlab.com/api/v4/projects/33089355/packages/npm:
    npmAuthToken: Wca3tGwxzH-rkmom8_Fb

npmScopes:
  atlasdevteam:
    npmRegistryServer: "https://gitlab.com/api/v4/packages/npm/"
  space-it-blockchain:
    npmRegistryServer: "https://gitlab.com/api/v4/projects/33089355/packages/npm/"

packageExtensions:
  "@flashbots/ethers-provider-bundle@*":
    dependencies:
      "@ethersproject/transactions": "*"
  "@uniswap/v3-sdk@*":
    dependencies:
      "@ethersproject/address": "*"